apiVersion: apps/v1
kind: Deployment
metadata:
  name: podfetch
spec:
  selector:
    matchLabels:
      app: podfetch
  template:
    metadata:
      labels:
        app: podfetch
    spec:
      containers:
      - name: podfetch
        image: fullaware/podfetch:latest
        env:
        - name: MSG
          value: "Hello World!!"
        ports:
        - name: http
          containerPort: 8080 
          protocol: TCP
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
